### ISSUE TITLE
Warning message about libjpeg.so.62 libjpeg.so.9 conflict

### ISSUE THREAD

**Issue by aliabdolali** [NOAA-EMC/WW3#924] opened 2023-03-02 02:24 UTC
**Describe the bug**
The following warning message is shown during WW3 build:

`/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: warning: libjpeg.so.62, needed by /apps/spack/jasper/2.0.25/intel/19.1.3.304/sjib74krrorkyczqpqah4tvewmlnqdx4/lib64/libjasper.so, may conflict with libjpeg.so.9`

**Here is the summary of investigations by NCO, @sbanihash on GLWUv2 implementation:** 

Digging more, the libjasper.so library is bound to _libjpeg.so.62_ while WW3 executables (i.e. _ww3_uprstr, ww3_trck, ww3_trck_) are linked to _libjpeg.so.9_.

During the build process, cmake creates a directory for all the components. Under each directory a link.txt file is generated and points to the old libjasper.so. Link.txt files can be found under:
`.. /sorc/WW3.fd/build_SHRD/model/src/CMakeFiles/<exec>.dir`

These directories also contain a _build.make_ file that includes both:

External object files for target 

 _/apps/spack/jasper/2.0.25/intel/19.1.3.304/sjib74krrorkyczqpqah4tvewmlnqdx4/lib64/libjasper.so_
_bin/ww3_grib: /apps/spack/libjpeg/9c/intel/19.1.3.304/jkr3isi257ktoouprwaxcn4twtye747z/lib/libjpeg.
.so_

These files are auto-generated by the build script. During clean up, these files are deleted, so to view the files you need to comment out the 'rm' commands in the the _make.all.sh_ script.

Potential Solution: 
Until the makefiles are corrected to include the actual version of jasper being used., we will continue to see the warnings, regardless of what jasper modules are actually being used during compiling.

## side notes: 

Loading and unloading the libjpeg module and ligjpeg-turbo will not solve this issue.
Neither will ordering the path to point to the libjpeg.so.62 first.

The issue is _libpeg.so_ v9 is not ABI backward compatible with the previous _libjpeg.so_ versions.
While _libjpeg-turbo.so_ is compatible with _libjpeg.so_ v8, it is not compatible with _libjpeg.so_ v9 and never will be. So any application using the _libjpeg.so_ v9 lib and linking to any library bound to the _libjpeg-turbo.so_ lib will produce this warning.

A secondary issue rebuilding jasper with libjpeg.so v9 will degrade performance due to loss of the turbo factor.

The current version of Jasper on WCOSS2  was built with libjpeg-turbo.  This is a fork of libjpeg that uses SIMD instructions to accelerate baseline JPEG encoding and decoding. This is the libjpeg.so.62. While libjpeg-turbo is compatible with and libjpeg v7 and v8, it is not compatible with libjpeg v9 (hence the warning). Building jasper with  libjpeg.so.9  will lose this acceleration.

Any shared object libraries that were required to be built using with lib-turbo will run into this issue when used with an application that uses libjpeg v9.

Here is the information about the why libjpeg v9 is not compatible with libjpeg-turbo.

![image](https://user-images.githubusercontent.com/37336972/222314395-55dd516c-af2c-44d7-908e-79598e779460.png)

**Comment by JessicaMeixner-NOAA** [comment] 2023-03-13 14:17
Current update on this is this is a specific issue with the g2 library on WCOSS2 and not a WW3 issue.  @sbanihash or @aerorahul please let me know if this is incorrect, if it's correct, we can perhaps close this issue if it's not a WW3 issue.

**Comment by aerorahul** [comment] 2023-03-13 14:27
The issue is not in WW3.  It is an artifact of CMake resolving the dependencies of `g2` correctly.

**Closed as completed** 2023-03-13 14:32 UTC
Labels: bug
