### ISSUE TITLE
ww3_tp2.17 has incorrect inp files 

### ISSUE THREAD

**Issue by mickaelaccensi** [NOAA-EMC/WW3#464] opened 2021-09-08 11:18 UTC
**Describe the bug**
ww3_multi_grdset_a1.inp and ww3_multi_grdset_c1.inp do not have the exact number of parameters which lead to a crash on the regtest

**To Reproduce**
`./bin/run_test -o both -f -S -T -c datarmor_intel -s MPI -s NO_PDLIB -w work_ma1 -m grdset_a1 -f -p $MPI_LAUNCH -n 28  -o all ../model ww3_tp2.17`
and
`./bin/run_test -o both -f -S -T -c datarmor_intel -s MPI -s PDLIB -w work_mc1 -m grdset_c1 -f -p $MPI_LAUNCH -n 28  -o all ../model ww3_tp2.17`

**Expected behavior**
 'inla'  'native' 'native' 'native' 'no' 'no' 'no' 'no'  1  1  0.00 1.00  F
should be replaced by
 'inla'  'native' 'native' 'native' 'no' 'no' 'no' 'no' 'no' 'no'   1  1  0.00 1.00  F

**Comment by aliabdolali** [comment] 2021-09-08 12:45
isn't it a duplicate of https://github.com/NOAA-EMC/WW3/issues/442?

**Comment by mickaelaccensi** [comment] 2021-09-08 13:02
> isn't it a duplicate of #442?

true, I'll close my issue and link to this one

**Closed as completed** 2021-09-08 13:03 UTC
Labels: bug
