### ISSUE TITLE
ww3: ww3_shel error

### ISSUE THREAD

**Issue by ZOUABBAS** [NOAA-EMC/WW3#270] opened 2020-12-05 19:38 UTC
i'm working with (WAVEWATCH III) ,i try to execute a simulation in slurm but i have this error , this is the first time i run a simulation with hpc  i work with ww3 in my comptuer and i never get this error 

my switch look like:
![3](https://user-images.githubusercontent.com/47395960/101261669-50037700-3739-11eb-90ab-191ba9126ce4.PNG)
my input shel look like
![4](https://user-images.githubusercontent.com/47395960/101261679-5e519300-3739-11eb-86f7-870d506c0896.PNG)
![5](https://user-images.githubusercontent.com/47395960/101261683-61e51a00-3739-11eb-9c2d-219ce51a8a73.PNG)
![6](https://user-images.githubusercontent.com/47395960/101261686-66113780-3739-11eb-9766-1f61426904c3.PNG)
and the error look like:
![01](https://user-images.githubusercontent.com/47395960/101261694-70333600-3739-11eb-824f-9ad4513adc71.PNG)
![129172096_715343362724915_5284531331425889262_n](https://user-images.githubusercontent.com/47395960/101261696-775a4400-3739-11eb-9819-1250e629061b.jpg)
can someone help me? i use the last version ww3-6.07.1

**Comment by ZOUABBAS** [comment] 2020-12-08 21:33
@thesser1 @mickaelaccensi @JessicaMeixner-NOAA @aliabdolali  help me please ?

**Comment by JessicaMeixner-NOAA** [comment] 2020-12-08 21:41
@ZOUABBAS When you build the model, can you add -g -traceback options to possibly get a more helpful error message?

**Comment by ZOUABBAS** [comment] 2020-12-08 21:45
where i put it this -g -traceback? is what when compiling./w3_setup .. -c * -s* -g -tracebackor where ?
    Le mardi 8 décembre 2020 à 22:41:36 UTC+1, Jessica Meixner <notifications@github.com> a écrit :  
 
 


@ZOUABBAS When you build the model, can you add -g -traceback options to possibly get a more helpful error message?

**Comment by thesser1** [comment] 2020-12-08 21:49
@ZOUABBAS debugging hpc runs are always difficult because they all operate a little differently.  When you submit your job to the compute nodes, are you making sure the compilers and libraries are all sourced.  On my system, I create a file listing all  libraries and environment variables that I use to compile the code and then I source that when creating the run script for my compute nodes just to make sure all libraries are linked.  

To answer your question to @JessicaMeixner-NOAA, you need to add the debug flags "-g -traceback" to your comp and link scripts when you set your compiler options.

**Comment by ZOUABBAS** [comment] 2020-12-08 21:54
@thesser1  you can give me a copy on the file that contains the libraries?

**Comment by thesser1** [comment] 2020-12-08 22:51
@ZOUABBAS I don't think it will help to have my file because it is specific to the hpc system I am running on.  However, I can give you a sense of what is in the file.  
1.) Define the compiler and mpi version used to build the code (if it is different than the system default)
2.) Define the WWATCH3_ENV variable.  This is where the wwatch3.env file is located
3.) Define the NETCDF_CONFIG variable. Location of the nf-config if using netcdf

I hope this helps.  Did you get a chance to recompile the code with debug flags?

**Comment by ZOUABBAS** [comment] 2020-12-08 23:24
yes , and i don't get a more helpful error messageand about the file that i have request , i have already created one, 
    Le mardi 8 décembre 2020 à 23:51:25 UTC+1, Ty Hesser <notifications@github.com> a écrit :  
 
 


@ZOUABBAS I don't think it will help to have my file because it is specific to the hpc system I am running on. However, I can give you a sense of what is in the file.
1.) Define the compiler and mpi version used to build the code (if it is different than the system default)
2.) Define the WWATCH3_ENV variable. This is where the wwatch3.env file is located
3.) Define the NETCDF_CONFIG variable. Location of the nf-config if using netcdf

I hope this helps. Did you get a chance to recompile the code with debug flags?

**Comment by ukmo-ccbunney** [comment] 2020-12-09 09:33
> yes , and i don't get a more helpful error messageand about the file that i have request

Hi  @ZOOUABBAS - after adding the `-g -traceback` flags to you comp script, make sure that you do a clean build first (run `w3_clean`, then run `w3_make`) otherwise you code will probably not be correctly re-compiled with the debugging turned on. This is because the build system won't rebuild objects if it doesn't need to.

**Comment by ZOUABBAS** [comment] 2020-12-09 09:45
hi @ukmo-ccbunney  the same error !!!

**Comment by ukmo-ccbunney** [comment] 2020-12-09 09:57
@ZOUBASS
I notice the the model is failing in the `w3iopomd` (point output) module.
I also notice that some of your point names are longer than 10 characters - this _probably is not_ causing the issue, but just to make sure, can you make all your pount names a max of 10 chars length? E.G. "DRAGONENA_BUOY" is too long, make it something like "DRAGN_BUOY".

By the way: future releases of WW3 will relax this 10 character point name restriction.

**Comment by ukmo-ccbunney** [comment] 2020-12-09 10:10
Also - what is on line 255 of `model/tmp/w3iopomd.F90`? (note that is the `tmp` directory, not the `ftn` directory)
That is the last (useful) point in the traceback.
This may give a clue as to what failed.

**Comment by ZOUABBAS** [comment] 2020-12-09 13:59
I minimize the number of points by removing buoy point and other points and it works, pourquoi ça c'est bien marché dans mon pc sachant que j'ai un pc qui n'est pas puissant. and i need all this point for bouandary conditions especially the 12 points  

    Le mercredi 9 décembre 2020 à 11:11:00 UTC+1, Chris Bunney <notifications@github.com> a écrit :  
 
 


Also - what is on line 255 of model/tmp/w3iopomd.F90?
That is the last point in the traceback that is in the WW3 code...
This may give a clue as to what failed. (not that is the tmp directory, not the ftn directory)

**Comment by ZOUABBAS** [comment] 2020-12-09 14:00
@ukmo-ccbunney I minimize the number of points by removing buoy point and other points and it works , why it worked well in my pc knowing that I have a pc that is not powerful
why it worked well in my pc knowing that I have a pc that is not powerful
and i need all this point for bouandary conditions especially the 12 points  

    Le mercredi 9 décembre 2020 à 14:59:44 UTC+1, Zoulikha ABBAS <abbas_zoulikha@yahoo.com> a écrit :  


    Le mercredi 9 décembre 2020 à 11:11:00 UTC+1, Chris Bunney <notifications@github.com> a écrit :  
 
 


Also - what is on line 255 of model/tmp/w3iopomd.F90?
That is the last point in the traceback that is in the WW3 code...
This may give a clue as to what failed. (not that is the tmp directory, not the ftn directory)

**Comment by ukmo-ccbunney** [comment] 2020-12-09 14:06
@ZOUABBAS - That's good that you got it running! We are definitely looking in the right place.
I doubt the the issue is with you PC not being powerful enough. It sounds more like memory problem.
Did you try changing the length of the buoy names to 10 characters or less?

**Comment by thesser1** [comment] 2020-12-09 14:13
@ZOUABBAS I agree with @ukmo-ccbunney.  I run with 100's of output points without a problem.  There is nothing in the code to keep the number of save points small.  I would add the buoys back in but reduce character length to 10 characters.

**Comment by ZOUABBAS** [comment] 2020-12-09 14:14
yes yes i try it but the error still . no you don't understand my problem actually i work with hpc and i get this error in hpcbut  before i run the same script in my pc with all the points and buoys and i had no errorfor this reason i tell you that my pc is not powerful it's just i want to understand the difference
    Le mercredi 9 décembre 2020 à 15:06:30 UTC+1, Chris Bunney <notifications@github.com> a écrit :  
 
 


@ZOUABBAS - That's good that you got it running! We are definitely looking in the right place.
I doubt the the issue is with you PC not being powerful enough. It sounds more like memory problem.
Did you try changing the length of the buoy names to 10 characters or less?

**Comment by ZOUABBAS** [comment] 2020-12-09 14:17
@ukmo-ccbunney  @thesser1  i will try your propositions and i tell you the result

**Comment by thesser1** [comment] 2020-12-09 14:22
@ZOUABBAS the only other thing I would suggest is change your dedicated output from a 2 to 1.  This is the number listed after you define the start and end time to your simulation and before you define output data.  Right now you have that set to use the last processor to handle all of your file writing.  I would switch this over to have no dedicated service process for writing.

**Comment by thesser1** [comment] 2020-12-14 16:50
@ZOUABBAS did these latest responses resolve your issue?  Let us know if the problem persists, otherwise, we will consider this issue closed.

**Comment by ZOUABBAS** [comment] 2020-12-14 17:18
@thesser1  no always when I decrease the number of points the error disappears and when I increase it comes back
but I guess it has a relation to node memory, does that make sense?
![74](https://user-images.githubusercontent.com/47395960/102112955-be7ebe00-3e38-11eb-8d36-4120be012aae.PNG)

**Comment by lherdman** [comment] 2021-02-01 20:56
I have found the same problem... did anyone figure out how to solve it?

**Comment by ZOUABBAS** [comment] 2021-02-01 21:09
Add Lost points or add an other point 0.0 0.0 
    Le lundi 1 février 2021, 21:56:20 UTC+1, lherdman <notifications@github.com> a écrit :  
 
 


I have found the same problem... did anyone figure out how to solve it?

**Comment by thesser1** [comment] 2021-02-02 15:04
@ZOUABBAS are you saying you were able to move past his issue by just adding an additional save point at 0.0 0.0?

**Comment by ZOUABBAS** [comment] 2021-02-02 18:17
this what I did to solve the problem after two months of testing
    Le mardi 2 février 2021, 16:05:17 UTC+1, Ty Hesser <notifications@github.com> a écrit :  
 
 


@ZOUABBAS are you saying you were able to move past his issue by just adding an additional save point at 0.0 0.0?

**Comment by lherdman** [comment] 2021-02-04 00:05
Unfortunately adding a zero zero point did not help me. I found that the issue appears when I attempt to implement mpi with the one file point output turned on. If I run on one core I can have all the point output go to one file, but if I run on multiple cores I get a seg fault if I try to to output to one file. I will now see if I can write out to multiple files with mpi. (I think it should work based on colleagues examples).  It is possible we have an extreme case with ~ 7000 output points.

**Comment by lherdman** [comment] 2021-02-04 00:07
perhaps this is a different issue... because I am using ww3_multi not ww3_shel

**Comment by thesser1** [comment] 2021-02-04 02:23
@lherdman are you saying the code is failing if you have a dedicated output core?  What value is the output server type?

**Comment by lherdman** [comment] 2021-02-04 14:18
This works:
$ -------------------------------------------------------------------- $
$ WAVEWATCH III multi-grid model driver input file                     $
$ -------------------------------------------------------------------- $
$
$ The first input line sets up the general multi-grid model definition
$ by defining the follwing six parameters :
$
$   1) Number of wave model grids.i                         ( NRGRD )
$   2) Number of grids definint input fields.               ( NRINP )
$   3) Flag for using unified point output file.           ( UNIPTS )
$   4) Output server type as in ww3_shel.inp
$   5) Flag for dedicated process for iunified point output.
$   6) Flag for grids sharing dedicated output processes.
$
  8 1 F 1 T T
$
$ -------------------------------------------------------------------- $
$ If there are input data grids defined ( NRINP > 0 ), then these
$ grids are defined first. These grids are defined as if they are wave
$ model grids using the file mod_def.MODID. Each grid is defined on
$ a separate input line with MODID, and eight input flags identifying
$ the presentce of 1) water levels 2) currents 3) winds 4) ice and
$ 5-7) assimilation data as in the file ww3_shel.inp.
$
 'gfdl'  F F T T F F F
$
$ In this example, we need the file mod_def.input to define the grid
$ and the file wind.input to provide the corresponding wind data.
$
$ -------------------------------------------------------------------- $
$ If all point output is gathered in a unified point output file
$ ( UNIPTS = .TRUE. ), then the output spectral grid needs to be
$ defined. Ths information is taken from a wave model grid, and only
$ the spectral definitions from this grid are relevant. Define the
$ name of this grid here
$
$ 'points'
$
$ In this example, we need the file mod_def.points to define the
....
Changing output server type to true and uncommenting the 'points' line does not work when using multiple cores. FYI, we are trying to output several thousand points.

**Comment by aliabdolali** [comment] 2021-07-14 17:38
Hi @lherdman is this issue solved? I am going to close it, but please reopen if it is still an issue.

**Closed as completed by aliabdolali** 2021-07-14 17:38 UTC
