### ISSUE TITLE
WW3 doesn't preprocess netcdf input data correctly if the time units are "days since 0001-01-01 00:00:00"

### ISSUE THREAD

**Issue by EmilioEchevarria** [NOAA-EMC/WW3#461] opened 2021-09-07 07:53 UTC
Hello,

I'm observing an issue when preprocessing netcdf input files with `ww3_prnc` with WW3 v6.07:

`ncdump -t -v time static/wind20170212.120000.nc` gives:

```
variables:
double time(time) ;
time:units = "days since 0001-01-01 00:00:00" ;

time = "2017-02-12 12", "2017-02-12 15", "2017-02-12 18", ...
```

After running `ww3_prnc`, `more ww3_prnc.out` gives:
```
Processing data
Time : 2017/02/14 12:00:00 UTC
reading ....
interpolating ....
writing ....
Time : 2017/02/14 15:00:00 UTC
reading ....
interpolating ....
writing ....
Time : 2017/02/14 18:00:00 UTC
reading ....
interpolating ....
writing ....
```

WW3 adds 2 days to the actual time. When I use input data with other time units it works fine:

`ncdump -t -v time static/wind20170212.120000.nc` gives:
```
variables:
double time(time) ;
time:units = "days since 1900-01-01 00:00:00" ;

time = "2017-02-12 12", "2017-02-12 15", "2017-02-12 18", ...
```

`more ww3_prnc.out` gives:
```
Processing data
Time : 2017/02/12 12:00:00 UTC
reading ....
interpolating ....
writing ....
Time : 2017/02/12 15:00:00 UTC
reading ....
interpolating ....
writing ....
Time : 2017/02/12 18:00:00 UTC
reading ....
interpolating ....
writing ....
```

I don't see this issue with WW3 v5.16, I believe it might be related to the changes implemented in `w3timemd.ftn` and `ww3_prnc.ftn`? 

Is this something worth implementing? I know I could always modify the workflow I have to execute WW3 to manipulate the input netcdf files and change the units.

Thanks!
Emilio

**Comment by mickaelaccensi** [comment] 2021-09-07 07:57
Hello Emilio,

could you provide the full list of attributes of the time variable of your netcdf file. It might be due to the calendar used in your file

Mickael

**Comment by EmilioEchevarria** [comment] 2021-09-07 08:45
Hello Mickael,

Thanks for getting in touch so quickly! 

These are the attributes of the file:
```
variables:
        double time(time) ;
                time:standard_name = "time" ;
                time:units = "days since 0001-01-01 00:00:00" ;
                time:calendar = "standard" ;
                time:axis = "T" ;
```

I tried changing these as well without much success. 

In your opinion this should work in WW3 v6.07? If yes, then I know there's something wrong with the input file I'm using. 

Thanks,
Emilio

**Comment by mickaelaccensi** [comment] 2021-09-07 09:44
ok the problem is because of the attribute units which starts at 0001. Could you provide me your netcdf file to try on my side

**Comment by EmilioEchevarria** [comment] 2021-09-08 00:04
[wind.zip](https://github.com/NOAA-EMC/WW3/files/7124859/wind.zip)

Thanks Mickael, I tried uploading the file in a zip, let me know if you can access it.

**Comment by mickaelaccensi** [comment] 2021-09-09 09:31
I'm also able to reproduce the problem. From what I understood, it seems to be related to the calendar reference. The standard calendar is gregorian. But because your base date is 0001-01-01 which is before the Gregorian origin date of 1582-10-15, it shoud be considered as proleptic_gregorian.

If you change the calendar attribute with nco tools : 
`ncatted -O -a calendar,time,o,c,'proleptic_gregorian' wind.nc wind.nc`

then if you do ncdump -v time -t wind.nc : 
```
 time = "2017-02-14 12", "2017-02-14 15", "2017-02-14 18", "2017-02-14 21", 
    "2017-02-15", "2017-02-15 03", "2017-02-15 06", "2017-02-15 09", 
    "2017-02-15 12", "2017-02-15 15", "2017-02-15 18", "2017-02-15 21",
```

So, with ncdump and the time conversion done through UDunits, I'm able to reproduce what is performed in WW3.

**Now the question is to know if you expect to have 2017-02-02 or 2017-02-04 ?
From where did you get this file ?
Have you defined on your own the base date 0001-01-01 ?**



cf convention is described here : 
https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch04s04.html
with an extract here : 
>  In order to calculate a new date and time given a base date, base time and a time increment one must know what calendar to use. For this purpose we recommend that the calendar be specified by the attribute calendar which is assigned to the time coordinate variable. The values currently defined for calendar are:
> 
> gregorian or standard
> 
>     Mixed Gregorian/Julian calendar as defined by Udunits. This is the default. 
> proleptic_gregorian
> 
>     A Gregorian calendar extended to dates before 1582-10-15. That is, a year is a leap year if either (i) it is divisible by 4 but not by 100 or (ii) it is divisible by 400.

**Comment by EmilioEchevarria** [comment] 2021-09-15 06:16
Hello Mickael, 

Thank you so much! I can see that the problem is related to the calendar reference, and therefore to my input file. I guess the reason I didn't observe this with WW3 v5.16 is that v5 is less strict with the time units. 

Best regards,
Emilio

**Comment by mickaelaccensi** [comment] 2021-09-20 09:15
no problem. So I close the issue.
Bests,
Mickael

**Closed as completed by mickaelaccensi** 2021-09-20 09:15 UTC
Labels: bug
