### ISSUE TITLE
Issues with ww3_ounf partition variables on orion 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#451] opened 2021-08-23 13:43 UTC
**Describe the bug**
When running ww3_ounf on orion with variables PHS PTP PDIR, we get the error: 

 
```
*** WAVEWATCH III ERROR IN OUNF :
LINE NUMBER 2187
NETCDF ERROR MESSAGE:
NetCDF: Name contains illegal characters

```

**To Reproduce**
Run ww3_ufs1.1 regression tests on orion or any ww3_ounf test with variables: PHS PTP PDIR 

**Expected behavior**
This works with the same modules on hera, so this should also work on orion. It's possible it's a hpc-stack/orion issue alone. 
@ricampos reported that switching to the non-hpc-stack module netcdf/4.7.2 solved the issue -- but we should be using hpc-stack modules and the same test with the same modules is working on hera.

**Comment by JessicaMeixner-NOAA** [comment] 2021-11-13 13:45
@ukmo-ccbunney I am curious if you have advice on what a good strategy for debugging this issue we're having on one of our research machines at NOAA with writing partitioned output to netcdf files.   I put some write statements in ww3_ounf right before we crash (https://github.com/JessicaMeixner-NOAA/WW3/blob/bug/ounfpartonorion/model/src/ww3_ounf.F90#L2746-L2753) and on the machine where things work, I know we should get the following output: 
```
 JDMOUNF META varnm:
 phs0

 JDMOUNF META varnl:
 wave significant height partition 0

 JDMOUNF META varns:
 sea_surface_wind_wave_significant_height

 JDMOUNF META varng:
 significant_wave_height_partition_0
```

and when we're getting the error we get: 
```
 JDMOUNF META varnm:
    0

 JDMOUNF META varnl:
                                   0

 JDMOUNF META varns:
 sea_surface_wind_wave_significant_height

 JDMOUNF META varng:
                                   0

  *** WAVEWATCH III ERROR IN OUNF :
  LINE NUMBER         2753
  NETCDF ERROR MESSAGE:
 NetCDF: Name contains illegal characters
```

So it appears that the partitioned name is not getting created correctly, causing the netcdf error.  On the two machines, the intel version is slightly different, which might be the issue here.  However, I just tried a more recent intel versions and that also did not work.    @ricampos has used an earlier version of netcdf with success, but I'm wondering what the actual variable names are in that case (or what other combinations of intel/netcdf you were using in that case, can you check when you get a chance and let me know?    It seems logical that netcdf does not like the "0"  variable names, but I'm not quite sure where/how best to figure out why it's not getting the right names in the first place.

**Comment by ricampos** [comment] 2021-11-15 20:37
Yes, I've been using "module load netcdf/4.7.2" in my codes and this version works perfectly. The problems are in the partition names, if you use ww3_ounf without partitions, then 4.7.4 will work fine, but when partitions are included it crashes. 
I don't know if this is the cause of the error, but you are right about the "0", for exemple: phs0 : long_name = "wave significant height partition 0" ;
but why does it happen in version netcdf/4.7.4 but not in netcdf/4.7.2 ?

**Comment by JessicaMeixner-NOAA** [comment] 2021-11-19 22:21
So I've been able to trace the issue to this line in [w3ounfmetamd.F90](https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3ounfmetamd.F90#L1793):
`        WRITE(INSTR,'(A,I1,A)') INSTR(1:I-1), IPART, INSTR(J:LEN(INSTR))
`
Before this line, if you print out INSTR(1:I-1), IPART, and INSTR(J:LEN(INSTR)) either version of NETCDF gives the same answer.  However if you write out INSTR after this line, on orion if you use netcdf 4.7.4 you just get "IPART", and if you use 4.7.2 you get the correct string of INSTR(1:I-1), IPART, INSTR(J:LEN(INSTR)).  This makes zero sense to me, because this "write" statement should not be impacted by what version of NetCDF we are using.

**Comment by ukmo-ccbunney** [comment] 2021-11-30 17:07
Something to try:

Can you add an ounfmeta.inp file to the input directory for that regtests that overrides the VARNL and VARNG attributes for PHS? Like this:
```
META PHS
  long_name = "Spectral significant <SPART> wave height"
  globwave_name = "Spectral significant <SPART> wave height"
```

Let's see if that makes any difference...

**Comment by JessicaMeixner-NOAA** [comment] 2021-12-03 18:41
The machine where this problem occurred was down for the past two days, but I finally got a chance to try this and it fails in the same way.  I added my name to the long_name to make sure it was taking the attributes since I had not used that before and confirmed that it was. I think @ukmo-ccbunney  assumption that netcdf is likely a misdirection and it is most likely an odd memory error is likely correct, but that's hard to track down.

**Comment by ukmo-ccbunney** [comment] 2021-12-07 10:49
@JessicaMeixner-NOAA : can you check if the same crash occurs if you use the `.inp` file rather than the `.nml` file?
I am seeing some suspicious behaviour with the Intel compiler when running with the nml variant...


EDIT: Actually, forget that - I can see you are already using the inp file in that regtest.

**Can you try changing the NetCDF version (not the netcdf var type) from 4 to 3? Does that stop the crash?** For me generating a netCDF4 file using the intel compiler on our HPC is causing a floating point error. I have to turn off `-fpe0` in the compile flags to get it to work. I was just wondering if it is in any way related. I don't get the same issue for NetCDF 3 files....

**Comment by JessicaMeixner-NOAA** [comment] 2021-12-07 20:31
@ukmo-ccbunney I actually read your comment wrong and I did try an .nml instead of a .inp file and they both fail the same way.   

Changing the NetCDF type variable from 4 to 3 also did not work (with nml or inp).   I'm not using the -fpe0 option in the compile flags, although I guess I should be running with some debug flags.  I thought I had tried that, but going to try again now.

**Comment by JessicaMeixner-NOAA** [comment] 2021-12-07 20:35
Well, it is at least consistent, recompiling and running with debug flags again fails in the same way.  Unfortunately, the mystery continues.

**Comment by ukmo-ccbunney** [comment] 2021-12-09 10:52
Hmmm... this is a difficult one to reproduce on my end, especially as I don't have that version of the netcdf libraries available to me.

I wonder if you could maybe run the program with the `valgrind` memory debugger? Perhaps that might shed some light on what sounds like an elusive memory bug?

**Comment by JessicaMeixner-NOAA** [comment] 2021-12-09 11:59
@ukmo-ccbunney it is extremely hard to reproduce as we cannot even reproduce it ourselves on our other HPC systems either.  I think the next step of valgrind is the way to go, it just likely will not happen quickly.

**Comment by ukmo-ccbunney** [comment] 2021-12-09 14:47
I'm doing some runs with valgrind here. Although I can't reproduce the error, if there is some suble memory bug then hopefully we can uncover it with valgrind.  I've got some cryptic warnings about overlapping source/destination memory locations in a `memcpy` which is making me suspicious...

I will continue my investigations and get back to you.

**Comment by ukmo-ccbunney** [comment] 2021-12-09 15:26
Aha! Right....I think I might understand what is happening now.
As I mention above, valgrind is complaining that a memcpy (low level libc call) is reading and writing to the same bit of memory. It turns out this relates to the same line in `w3ounfmetamd.f90` you mention above:
```
WRITE(INSTR,'(A,I1,A)') INSTR(1:I-1), IPART, INSTR(J:LEN(INSTR))
```

After staring at this for awhile, I think I know what is happening. This is an "internal" formatted write to a string (INSTR). However, it is using INSTR as an input to the write so it is writing over the memory that it is trying to read from. I guess this is a bit like cat`ing a file in a terminal shell and redirecting the output to the same file...

All the other operations on INSTR in that subroutine use assignement operators, e.g.
```
       INSTR = INSTR(1:I-1) // TRIM(SNAMEP(ISN)) // INSTR(J:LEN(INSTR))
```
which is fine as a temporary string is created on the RHS before it is assigned to the LHS.

Unfortunately, I am pretty sure the same does not apply for the internal WRITE.

So - long story short - I've replaced the original line with the following:
```
        WRITE(TMP, '(A,I1,A)') INSTR(1:I-1), IPART, INSTR(J:LEN(INSTR))
        INSTR = TMP
```
and I no longer have any "overlapping memcpy" warnings.

Now - I could not reproduce your issue, but I am fairly sure this is the root cause of it. Why the netCDF library version should affect the behavior I don't know, but there are lots of things about underlying O/S behavior that I don't understand!

Can you try re-running with this branch and let me know if it fixes the issue for you:
https://github.com/ukmo-waves/WW3/tree/bugfix/ounfpartno

If it works, I'll raise a PR.
Fingers crossed!

**Comment by JessicaMeixner-NOAA** [comment] 2021-12-09 15:52
@ukmo-ccbunney I'm trying now! Fingers crossed!!!

**Comment by JessicaMeixner-NOAA** [comment] 2021-12-09 17:58
Thank you @ukmo-ccbunney !!!!!!   That worked, yay!!!!!!!!!!

**Comment by aliabdolali** [comment] 2021-12-09 18:24
Thanks @ukmo-ccbunney and @JessicaMeixner-NOAA 
I'll put the PR in the queue once it is made.

**Comment by JessicaMeixner-NOAA** [comment] 2021-12-09 21:21
I can confirm that we can run the entire matrix of regression tests now on orion without error with this branch.

**Comment by ukmo-ccbunney** [comment] 2021-12-09 23:00
Great! What a cheeky little gremlin that was....

**Closed as completed** 2021-12-15 15:21 UTC
Labels: bug
